apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: {{ .Values.namespace }}
  labels:
    app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-deployment-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata:

    output.elasticsearch:
      hosts: {{ .Values.elastic.host }}
