apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: {{ .Values.namespace }}
  labels:
    app: metricbeat
data:
  airflow.yml: |-
    - module: airflow
      host: ${STATSD_HOST}
      metricsets:
        - statsd